Use signal names w/o a SIG prefix, which is a bashism

diff --git a/freebsd-sendpr/debian/patches/004_bashims.patch b/freebsd-sendpr/debian/patches/004_bashims.patch
--- a/freebsd-sendpr/debian/patches/004_bashims.patch
+++ b/freebsd-sendpr/debian/patches/004_bashims.patch
@@ -9,7 +9,7 @@
  xs=0
  trap 'rm -f $REF $TEMP; exit $xs' 0
 -trap 'SAV=`mktemp -t pr`;echo "$COMMAND: Aborting ... saving unfinished PR into $SAV"; rm -f $REF ; mv $TEMP $SAV; xs=1; exit' 1 2 3 13 15
-+trap 'SAV=`mktemp -t pr`;echo "$COMMAND: Aborting ... saving unfinished PR into $SAV"; rm -f $REF ; mv $TEMP $SAV; xs=1; exit' SIGHUP SIGINT SIGQUIT SIGPIPE SIGTERM
++trap 'SAV=`mktemp -t pr`;echo "$COMMAND: Aborting ... saving unfinished PR into $SAV"; rm -f $REF ; mv $TEMP $SAV; xs=1; exit' HUP INT QUIT PIPE TERM
  
  # If they told us to use a specific file, then do so.
  if [ -n "$IN_FILE" ]; then
