Improve init script: Better support fancy outputs; Improve failure toleance of the reload handler; Log istgt start output to syslog; prepare for upload

diff --git a/istgt/debian/init b/istgt/debian/init
--- a/istgt/debian/init
+++ b/istgt/debian/init
@@ -15,6 +15,7 @@ PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="istgt iSCSI target"
 NAME=istgt
 DAEMON=/usr/sbin/istgt
+ISTGTCONTROL=/usr/sbin/istgtcontrol
 PIDFILE=/var/run/$NAME.pid
 DAEMON_ARGS="-c /etc/istgt/istgt.conf -p $PIDFILE"
 SCRIPTNAME=/etc/init.d/$NAME
@@ -50,13 +51,13 @@ do_start()
 	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
 		|| return 1
 	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
+		$DAEMON_ARGS  2>&1 | logger -p daemon.info \
 		|| return 2
 
 	RETVAL=0
 	for i in 1 2 3 4 5 ; do
 		sleep 1
-		status_of_proc -p $PIDFILE "$DAEMON" "$NAME" || RETVAL=$?
+		pidofproc -p $PIDFILE "$DAEMON" "$NAME" > /dev/null || RETVAL=$?
 		[ "$RETVAL" = 0 ] && return 0
 	done
 
@@ -89,7 +90,10 @@ do_stop()
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
-	istgtcontrol refresh
+	[ -x $ISTGTCONTROL ] || return 127
+	pidofproc -p $PIDFILE $NAME > /dev/null || return 2
+	$ISTGTCONTROL refresh > /dev/null 2>&1
+	return $?
 }
 
 case "$1" in
@@ -113,8 +117,20 @@ case "$1" in
     [ "$VERBOSE" != no ] && log_daemon_msg "Reloading $DESC " "$NAME"
     do_reload
     case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0)
+			[ "$VERBOSE" != no ] && log_end_msg 0
+			;;
+		2)
+			[ "$VERBOSE" != no ] && log_end_msg 1
+			[ "$VERBOSE" != no ] && log_warning_msg "$NAME is not running"
+			;;
+		127)
+			[ "$VERBOSE" != no ] && log_end_msg 1
+			[ "$VERBOSE" != no ] && log_warning_msg "$ISTGTCONTROL not found"
+			;;
+		*)
+			[ "$VERBOSE" != no ] && log_end_msg 1
+			;;
 	esac
   ;;
   status)
