Release Ging 0.0.2.

diff --git a/web/ging/scripts.diff b/web/ging/scripts.diff
--- a/web/ging/scripts.diff
+++ b/web/ging/scripts.diff
@@ -1,6 +1,6 @@
 Index: livecd.sh
 ===================================================================
---- livecd.sh	(revision 565)
+--- livecd.sh	(revision 575)
 +++ livecd.sh	(working copy)
 @@ -13,7 +13,7 @@
  
@@ -20,20 +20,77 @@ Index: livecd.sh
  
  ##################
  #  add some trickery
-@@ -152,28 +150,23 @@
+@@ -104,41 +102,30 @@
+ mkfs.ufs /dev/md0
+ mount -o rw -t ufs /dev/md0 /ramdisk
+ echo "Populating ramdisk node \(this might take a while\) ..."
++
++for i in bin usr boot lib libexec sbin var/lib/{dpkg,apt}
++  var/cache/apt ; do
++  mkdir -p /ramdisk/\$i
++  mount -t nullfs /\$i /ramdisk/\$i
++done
++
++mkdir -p /ramdisk/{dev,proc}
++mount -t devfs null /ramdisk/dev
++
+ for i in /* ; do
+-  case \${i} in
+-    /bin|/usr|/boot|/lib|/libexec|/sbin|/base)
+-      mkdir -p /ramdisk/\${i}
+-      mount -t nullfs /\${i} /ramdisk/\${i}
++  case \$i in
++    /dev|/proc|/bin|/usr|/boot|/lib|/libexec|/sbin|/base|/ramdisk|/*-RELEASE)
+     ;;
+-    /dev)
+-      mkdir -p /ramdisk/dev
+-      mount -t devfs null /ramdisk/dev
+-    ;;
+-    /proc)
+-      mkdir -p /ramdisk/proc
+-      mount -t linprocfs null /ramdisk/proc
+-    ;;
+     /var)
+-      mkdir -p /ramdisk/var
+-      for i in \${i}/* ; do
+-        case \${i} in
+-          /var/lib|/var/cache)
+-            mkdir -p /ramdisk/\${i}
+-            mount -t nullfs /\${i} /ramdisk/\${i}
+-          ;;
+-          *)
+-            cp -a /\${i} /ramdisk/\${i}
+-          ;;
+-        esac
+-      done
++      # will fail for /var/lib/{dpkg,apt} and /var/cache/apt
++      cp -a \$i /ramdisk/\$i 2>/dev/null || true
+     ;;
+-    /ramdisk|/*-RELEASE)
++    *)
++      cp -a \$i /ramdisk/\$i
+     ;;
+-    /*)
+-      cp -a /\${i} /ramdisk/\${i}
+-    ;;
+   esac
+ done
++
+ # doesn't work as expected (i.e. you still need -f to halt)
+ #mknod -m 600 /ramdisk/etc/.initctl p
+ export TERM=cons25
+@@ -152,28 +139,19 @@
  # (we don't use <<EOF because bash requires a tempfile to do that)
  echo "/dev/md0	/	ufs		rw	1 1" > /ramdisk/etc/fstab
  
 -while chroot /ramdisk ; do true ; done
 -echo "chrooted shell exitted with non-zero status.  NOT respawning."
-+# spawn chrooted init using -i hack
-+cp /usr/share/sysvinit/inittab /ramdisk/etc/
-+chroot /ramdisk init -i
-+echo
-+echo "chrooted init died!!  Spawning a rescue shell."
- while bash ; do true ; done
+-while bash ; do true ; done
 -echo "Ok, you get what you wanted ..."
- halt -f
+-halt -f
++# exec chrooted init using -i hack
++cp /usr/share/sysvinit/inittab /ramdisk/etc/
++exec chroot /ramdisk init -i
  __EOF__
  chmod +x root/startup
  
@@ -57,17 +114,9 @@ Index: livecd.sh
  cd ${pwd}/
 Index: tarball.sh
 ===================================================================
---- tarball.sh	(revision 562)
+--- tarball.sh	(revision 575)
 +++ tarball.sh	(working copy)
-@@ -2,14 +2,14 @@
- #
- # Build-Depends: mkisofs, crosshurd, fakeroot
- #
--# Copyright 2004  Robert Millan <rmh@debian.org>
-+# Copyright 2004, 2005  Robert Millan <rmh@aybabtu.com>
- # See /usr/share/common-licenses/GPL for license terms.
- 
- set -ex
+@@ -9,7 +9,7 @@
  
  if [ "$UID" != "0" ] ; then
    # I call that incest, don't you?
@@ -76,18 +125,9 @@ Index: tarball.sh
    exit 0
  fi
  
-@@ -21,7 +21,7 @@
- cpu="i486"
- system="kfreebsd-gnu"
- uname="GNU/kFreeBSD"
--tmp1=`tempfile` && rm -f ${tmp1} && mkdir -p ${tmp1}
-+tmp1=`mktemp -d`
- pwd=`pwd`
- export GZIP=--best
- 
-@@ -40,6 +40,74 @@
- # maybe-missing kernel package
- cd ${tmp1} && dpkg --extract var/cache/apt/archives/kfreebsd-image-5.*.deb .
+@@ -52,6 +52,74 @@
+ __EOF__
+ fi
  
 +################################################################################
 +# BEGIN GING-SPECIFIC STUFF
